# enable polkit (super user support)
exec-once = systemctl --user start hyprpolkitagent

# Start the notification panel
exec-once = swaync

# Start the top bar
exec-once = waybar

# autostart applications support
exec-once = dex -a

# pipewire patch bay
exec = qpwgraph -m

# When idle for a long time
exec-once = hypridle

# start nightlight
exec-once = hyprsunset

# nwg-look initialize
exec = nwg-look -a

# external disk insert notification support
exec-once = udiskie --notify --no-automount

# Wallpaper handler
exec-once = swww-daemon
