windowrule = float 1, match:class ^(nwg-displays)$
windowrule = float 1, match:class ^(org.pulseaudio.pavucontrol)$
windowrule = float 1, match:class ^(nm-connection-editor)$
windowrule = float 1, match:class ^(qt6ct)$
windowrule = float 1, match:class ^(feh)$
windowrule = float 1, match:class ^(qpwgraph|org.rncbc.qpwgraph)$
windowrule = float 1, match:class ^(nwg-look)$
windowrule = float 1, match:class ^(org.gimp.GIMP)$
windowrule = float 1, match:class ^(org.ksnip.ksnip)$
windowrule = float 1, match:class ^(wallpaper-picker)$
windowrule = float 1, match:class ^(floating-calendar)$
windowrule = float 1, match:class ^(soundmixer)$
windowrule = float 1, match:class ^(Weather)$
windowrule = float 1, match:class ^(languages)$
windowrule = float 1, match:class ^(system-monitor)$

windowrule = float 1, match:class ^(Wofi)$
windowrule = opacity 0.8, match:class ^(wofi)$



windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}
